# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: asn digital services
name: anton stepan
email: info@antonstepan.it
description: > # this means to ignore newlines until "baseurl:"
  Als Full Service Dienstleister bieten wir Ihnen Unterstützung bei jeglichen Schritten Ihrer Software Projekte.

baseurl: "" # the subpath of your site, e.g. /antonstepan-it
url: "http://antonstepan.de" # the base hostname & protocol for your site


# Footer links
footer:
    social:
        email: info@antonstepan.it
        facebook: anton.stepan
        github: hknd
        linkedin: antonstepan
        googleplus: u/0/+AntonStepan
        instagram: asnftw

# Build settings
markdown: kramdown
